services:
  papermc:
    container_name: papermc
    image: mc:1
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - ./papermc:/papermc