services:
  papermc:
    container_name: papermc
    image: alpine:latest
    command: ["cd papermc && ls"]
    restart: always
    ports:
      - "25565:25565"
    volumes:
      - /papermc
      - ./mc.sh:/papermc