services:
  papermc:
    container_name: papermc
    image: alpine:latest
    working_dir: /papermc
    command: ["./mc.sh"]
    restart: no
    ports:
      - "25565:25565"
    volumes:
      - /papermc
      - ./mc.sh:/papermc