services:
  papermc:
    container_name: papermc
    image: mc:1
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "25565:25565"
      - "8804:8804"
    volumes:
      - ./papermc:/papermc
      - ./assets/server.properties:/papermc/server.properties
      - ./assets/plugins:/papermc/plugins