services:
  papermc:
    container_name: papermc
    image: alpine:latest
    command: ["./mc.sh"]
    restart: always
    ports:
      - "25565:25565"
    volumes:
      - ./mc.sh:/home
      - /papermc